BeginPackage["ToneAr`RocketChat`", {"ToneAr`RocketChat`Private`"}];
Begin["`FileScope`Globals`Private`"];

$icon =
	Show[
		Import[
			PacletObject["ToneAr/RocketChat"]["AssetLocation", "icon.svg"],
			"Graphics"
		],
		"ImageSize" -> Scaled[0.1]
	];

$headers = {"Content-Type" -> "application/json"};

$multipartHeaders = {"Content-Type" -> "multipart/form-data"};

$headerParameterMap =
	<|
		"authToken"       -> "X-Auth-Token",
		"authUserId"      -> "X-User-Id",
		"twoFactorCode"   -> "x-2fa-code",
		"twoFactorMethod" -> "x-2fa-method",
		"visitorToken"    -> "x-visitor-token"
	|>;

$connectionParameterNames = {"host", "authToken", "authUserId"};

$parameterMap =
	<|
		"Host"                           -> "host",
		"AuthToken"                      -> "authToken",
		"AuthUserID"                     -> "authUserId",
		"User"                           -> "user",
		"Password"                       -> "password",
		"Resume"                         -> "resume",
		"Code"                           -> "code",
		"ServiceName"                    -> "serviceName",
		"AccessToken"                    -> "accessToken",
		"Secret"                         -> "secret",
		"ExpiresIn"                      -> "expiresIn",
		"AccessTokenSecret"              -> "accessTokenSecret",
		"AppSecret"                      -> "appSecret",
		"AppID"                          -> "appId",
		"IDToken"                        -> "idToken",
		"Scope"                          -> "scope",
		"EmailOrUsername"                -> "emailOrUsername",
		"Name"                           -> "name",
		"Email"                          -> "email",
		"Username"                       -> "username",
		"Active"                         -> "active",
		"Nickname"                       -> "nickname",
		"Bio"                            -> "bio",
		"JoinDefaultChannels"            -> "joinDefaultChannels",
		"StatusText"                     -> "statusText",
		"Roles"                          -> "roles",
		"RequirePasswordChange"          -> "requirePasswordChange",
		"SetRandomPassword"              -> "setRandomPassword",
		"SendWelcomeEmail"               -> "sendWelcomeEmail",
		"Verified"                       -> "verified",
		"CustomFields"                   -> "customFields",
		"Pass"                           -> "pass",
		"SecretURL"                      -> "secretURL",
		"UserID"                         -> "userId",
		"Data"                           -> "data",
		"AvatarURL"                      -> "avatarUrl",
		"Message"                        -> "message",
		"Status"                         -> "status",
		"ActiveStatus"                   -> "activeStatus",
		"ConfirmRelinquish"              -> "confirmRelinquish",
		"DaysIdle"                       -> "daysIdle",
		"Role"                           -> "role",
		"TokenName"                      -> "tokenName",
		"BypassTwoFactor"                -> "bypassTwoFactor",
		"Description"                    -> "description",
		"Subject"                        -> "subject",
		"Emails"                         -> "emails",
		"Permissions"                    -> "permissions",
		"Mandatory2FA"                   -> "mandatory2fa",
		"RoleID"                         -> "roleId",
		"RoomID"                         -> "roomId",
		"ActiveUsersOnly"                -> "activeUsersOnly",
		"ReadOnly"                       -> "readOnly",
		"Members"                        -> "members",
		"ExcludeSelf"                    -> "excludeSelf",
		"ExtraData"                      -> "extraData",
		"RoomName"                       -> "roomName",
		"Announcement"                   -> "announcement",
		"Purpose"                        -> "purpose",
		"Topic"                          -> "topic",
		"Type"                           -> "type",
		"Encrypted"                      -> "encrypted",
		"UserIDs"                        -> "userIds",
		"JoinCode"                       -> "joinCode",
		"Default"                        -> "default",
		"ChannelID"                      -> "channelId",
		"Notifications"                  -> "notifications",
		"Latest"                         -> "latest",
		"Oldest"                         -> "oldest",
		"Inclusive"                      -> "inclusive",
		"ExcludePinned"                  -> "excludePinned",
		"FilesOnly"                      -> "filesOnly",
		"Users"                          -> "users",
		"Limit"                          -> "limit",
		"IgnoreDiscussion"               -> "ignoreDiscussion",
		"IgnoreThreads"                  -> "ignoreThreads",
		"Favorite"                       -> "favorite",
		"RID"                            -> "rid",
		"RoomDescription"                -> "roomDescription",
		"RoomAvatar"                     -> "roomAvatar",
		"Featured"                       -> "featured",
		"RoomTopic"                      -> "roomTopic",
		"RoomAnnouncement"               -> "roomAnnouncement",
		"RoomCustomFields"               -> "roomCustomFields",
		"RoomType"                       -> "roomType",
		"ReactWhenReadOnly"              -> "reactWhenReadOnly",
		"SystemMessages"                 -> "systemMessages",
		"StreamingOptions"               -> "streamingOptions",
		"RetentionEnabled"               -> "retentionEnabled",
		"RetentionMaxAge"                -> "retentionMaxAge",
		"RetentionExcludePinned"         -> "retentionExcludePinned",
		"RetentionFilesOnly"             -> "retentionFilesOnly",
		"RetentionIgnoreThreads"         -> "retentionIgnoreThreads",
		"RetentionOverrideGlobal"        -> "retentionOverrideGlobal",
		"Sidepanel"                      -> "sidepanel",
		"Action"                         -> "action",
		"DateFrom"                       -> "dateFrom",
		"DateTo"                         -> "dateTo",
		"Format"                         -> "format",
		"ToUsers"                        -> "toUsers",
		"ToEmails"                       -> "toEmails",
		"Messages"                       -> "messages",
		"Reply"                          -> "reply",
		"File"                           -> "file",
		"FileID"                         -> "fileId",
		"Emoji"                          -> "emoji",
		"Groupable"                      -> "groupable",
		"Msg"                            -> "msg",
		"Avatar"                         -> "avatar",
		"Alias"                          -> "alias",
		"ParameterlessBody"              -> "ParameterlessBody",
		"Key"                            -> "key",
		"Values"                         -> "values",
		"Usernames"                      -> "usernames",
		"IDs"                            -> "ids",
		"LDAPIDs"                        -> "ldapIds",
		"ReadThreads"                    -> "readThreads",
		"FirstUnreadMessage"             -> "firstUnreadMessage",
		"Room"                           -> "room",
		"Owner"                          -> "owner",
		"TeamID"                         -> "teamId",
		"Member"                         -> "member",
		"Rooms"                          -> "rooms",
		"TeamName"                       -> "teamName",
		"RoomsToRemove"                  -> "roomsToRemove",
		"IsDefault"                      -> "isDefault",
		"Days"                           -> "days",
		"MaxUses"                        -> "maxUses",
		"Token"                          -> "token",
		"AsUser"                         -> "asUser",
		"MessageID"                      -> "messageId",
		"Reaction"                       -> "reaction",
		"ShouldReact"                    -> "shouldReact",
		"Text"                           -> "text",
		"PreviewURLs"                    -> "previewUrls",
		"ParseURLs"                      -> "parseUrls",
		"Attachments"                    -> "attachments",
		"Channel"                        -> "channel",
		"Field"                          -> "field",
		"Value"                          -> "value",
		"DefaultLanguage"                -> "defaultLanguage",
		"TargetLanguage"                 -> "targetLanguage",
		"AgentID"                        -> "agentId",
		"AgentData"                      -> "agentData",
		"AgentDepartments"               -> "agentDepartments",
		"Visitor"                        -> "visitor",
		"VisitorID"                      -> "visitorId",
		"Phone"                          -> "phone",
		"ContactManager"                 -> "contactManager",
		"Phones"                         -> "phones",
		"ContactID"                      -> "contactId",
		"WipeConflicts"                  -> "wipeConflicts",
		"GuestData"                      -> "guestData",
		"RoomData"                       -> "roomData",
		"DepartmentID"                   -> "departmentId",
		"PriorityID"                     -> "priorityId",
		"Comment"                        -> "comment",
		"ForceClose"                     -> "forceClose",
		"Tags"                           -> "tags",
		"GenerateTranscriptPDF"          -> "generateTranscriptPdf",
		"TranscriptEmail"                -> "transcriptEmail",
		"Department"                     -> "department",
		"Agents"                         -> "agents",
		"DepartmentUnit"                 -> "departmentUnit",
		"Upsert"                         -> "upsert",
		"Remove"                         -> "remove",
		"Overwrite"                      -> "overwrite",
		"CustomFieldID"                  -> "customFieldId",
		"CustomFieldData"                -> "customFieldData",
		"TimezoneName"                   -> "timezoneName",
		"DaysOpen"                       -> "daysOpen",
		"DepartmentsToApplyBusinessHour" -> "departmentsToApplyBusinessHour",
		"WorkHours"                      -> "workHours",
		"TagID"                          -> "tagId",
		"ID"                             -> "id",
		"TagData"                        -> "tagData",
		"TagDepartments"                 -> "tagDepartments",
		"UnitData"                       -> "unitData",
		"UnitMonitors"                   -> "unitMonitors",
		"UnitDepartments"                -> "unitDepartments",
		"UnitID"                         -> "unitId",
		"DueTimeInMinutes"               -> "dueTimeInMinutes",
		"SLAID"                          -> "slaId",
		"Shortcut"                       -> "shortcut",
		"InquiryID"                      -> "inquiryId",
		"Service"                        -> "service",
		"From"                           -> "from",
		"To"                             -> "to",
		"Body"                           -> "body",
		"Enabled"                        -> "enabled",
		"RunOnce"                        -> "runOnce",
		"Conditions"                     -> "conditions",
		"Actions"                        -> "actions",
		"WebhookURL"                     -> "webhookUrl",
		"Timeout"                        -> "timeout",
		"FallbackMessage"                -> "fallbackMessage",
		"Agent"                          -> "agent",
		"PageInfo"                       -> "pageInfo",
		"ScriptEnabled"                  -> "scriptEnabled",
		"Script"                         -> "script",
		"Event"                          -> "event",
		"URLs"                           -> "urls",
		"TriggerWords"                   -> "triggerWords",
		"SkipTranspile"                  -> "skipTranspile",
		"IntegrationID"                  -> "integrationId",
		"TargetChannel"                  -> "targetChannel",
		"AccountID"                      -> "accountId",
		"RedirectURI"                    -> "redirectUri",
		"BannerID"                       -> "bannerId",
		"AppName"                        -> "appName",
		"Asset"                          -> "asset",
		"AssetName"                      -> "assetName",
		"RefreshAllClients"              -> "refreshAllClients",
		"Aliases"                        -> "aliases",
		"EmojiID"                        -> "emojiId",
		"StatusType"                     -> "statusType",
		"CustomUserStatusID"             -> "customUserStatusId",
		"Color"                          -> "color",
		"Editor"                         -> "editor",
		"Execute"                        -> "execute",
		"CloudBlob"                      -> "cloudBlob",
		"KeyID"                          -> "keyID",
		"UID"                            -> "uid",
		"BinaryContent"                  -> "binaryContent",
		"ImporterKey"                    -> "importerKey",
		"FileName"                       -> "fileName",
		"ContentType"                    -> "contentType",
		"FileURL"                        -> "fileUrl",
		"Input"                          -> "input",
		"ServerName"                     -> "serverName",
		"ExternalRoomID"                 -> "externalRoomId",
		"Title"                          -> "title",
		"AllowRinging"                   -> "allowRinging",
		"CallID"                         -> "callId",
		"State"                          -> "state",
		"Reason"                         -> "reason",
		"SessionID"                      -> "sessionId",
		"Method"                         -> "method",
		"SenderInfo"                     -> "senderInfo",
		"SMTP"                           -> "smtp",
		"IMAP"                           -> "imap",
		"StartTime"                      -> "startTime",
		"EndTime"                        -> "endTime",
		"ReminderMinutesBeforeStart"     -> "reminderMinutesBeforeStart",
		"Busy"                           -> "busy",
		"ExternalID"                     -> "externalId",
		"EventID"                        -> "eventId",
		"ActionData"                     -> "actionData",
		"PhoneNumbers"                   -> "phoneNumbers",
		"ConnectedWhatsAppNumber"        -> "connectedWhatsAppNo",
		"TargetAgent"                    -> "targetAgent",
		"TargetDepartment"               -> "targetDepartment",
		"Template"                       -> "template",
		"License"                        -> "license",
		"Command"                        -> "command",
		"Parameters"                     -> "params",
		"TriggerID"                      -> "triggerId",
		"PreviewItem"                    -> "previewItem",
		"DryRun"                         -> "dryrun",
		"CreatedAt"                      -> "createdAt"
	|>;

$parameterNameAcronyms =
	<|
		"2fa"   -> "2FA",
		"abac"  -> "ABAC",
		"api"   -> "API",
		"dns"   -> "DNS",
		"e2e"   -> "E2E",
		"id"    -> "ID",
		"ids"   -> "IDs",
		"imap"  -> "IMAP",
		"ldap"  -> "LDAP",
		"mid"   -> "MID",
		"oauth" -> "OAuth",
		"pdf"   -> "PDF",
		"pmid"  -> "PMID",
		"prid"  -> "PRID",
		"rid"   -> "RID",
		"sla"   -> "SLA",
		"smtp"  -> "SMTP",
		"sms"   -> "SMS",
		"tmid"  -> "TMID",
		"uid"   -> "UID",
		"uri"   -> "URI",
		"url"   -> "URL",
		"urls"  -> "URLs"
	|>;

formalParameterWord[word_String] :=
	Lookup[
		$parameterNameAcronyms,
		ToLowerCase[word],
		ToUpperCase @ StringTake[word, 1] <> ToLowerCase @ StringDrop[word, 1]
	];

generatedFormalParameterName[raw_String] :=
	Module[{words},
		words =
			DeleteCases[
				StringSplit[
					StringReplace[
						raw,
						{
							RegularExpression["([a-z0-9])([A-Z])"] -> "$1 $2",
							RegularExpression["(^_+|_+$)"]          -> "",
							RegularExpression["[_\\-\\[\\]]+"]      -> " "
						}
					],
					WhitespaceCharacter..
				],
				""
			];
		StringJoin[formalParameterWord /@ words]
	];

formalParameterName[raw_String] :=
	Lookup[
		AssociationThread[Values[$parameterMap], Keys[$parameterMap]],
		raw,
		generatedFormalParameterName[raw]
	];

requestParameterMap[rawParameters_List] :=
	AssociationThread[formalParameterName /@ rawParameters, rawParameters];

$defaultHost = "https://rocketchat.example.com";

End[];
EndPackage[];
